; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for BeatTheSpaceShip:
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_ARPEGGIO = 1

.export _music_data_beatthespaceship:=music_data_beatthespaceship

music_data_beatthespaceship:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : Deep Space
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : CanCan
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_beatthespaceship
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env6,@env7,@env0 ; 00 : Instrument 1
	.word @env8,@env6,@env10,@env0 ; 01 : Instrument 5
	.word @env3,@env11,@env9,@env0 ; 02 : Instrument 2
	.word @env4,@env11,@env9,@env0 ; 03 : Instrument 4
	.word @env5,@env6,@env9,@env0 ; 04 : Instrument 3

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$cb,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$00,$11
@env2:
	.byte $c0,$c0,$b4,$b4,$00,$00
@env3:
	.byte $00,$cf,$cd,$cb,$c8,$c7,$c5,$c4,$c1,$c0,$00,$09
@env4:
	.byte $00,$cf,$7f,$00,$02
@env5:
	.byte $00,$cf,$cf,$ce,$ce,$cd,$cc,$cb,$c9,$c8,$c6,$c4,$c3,$c1,$c0,$00,$0e
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $c0,$c2,$c1,$00,$02
@env8:
	.byte $00,$cf,$cc,$ca,$c9,$c7,$c6,$c5,$c4,$c3,$00,$09
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $c2,$c1,$c0,$00,$02
@env11:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 00 KICK (Pitch:15)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40 ; 01 SNARE (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $80
@song0ref2:
	.byte $16, $ad, $19, $ad, $1d, $ad, $20, $ad, $48, $22, $ff, $bd, $48, $11, $ad, $14, $ad, $18, $ad, $1d, $ad, $48, $24, $ff
	.byte $bd, $48
	.byte $41, $14
	.word @song0ref2
	.byte $dd, $20, $dd
@song0ch0loop:
	.byte $4c, $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song0ref39:
	.byte $16, $95, $11, $95, $19, $95, $14, $95, $1d, $95, $19, $95, $20, $95, $1d, $95, $48, $22, $dd, $25, $ad, $22, $ad, $48
	.byte $24, $dd, $22, $ad, $20, $ad, $48, $22, $ad, $1d, $dd, $18, $ad, $48, $11, $95, $0d, $95, $14, $95, $0f, $95, $18, $95
	.byte $14, $95, $1d, $95, $18, $95, $48, $24, $dd, $20, $dd, $48, $22, $ad, $1d, $dd, $1b, $ad, $48, $1d, $ad, $18, $dd, $14
	.byte $ad, $48
	.byte $41, $42
	.word @song0ref39
	.byte $48
	.byte $41, $42
	.word @song0ref39
	.byte $48, $7f, $4b, .lobyte(@env2), .hibyte(@env2), $82, $11, $ff, $bd, $48, $4d, $14, $ff, $bd, $48, $4d, $18, $ff, $bd
	.byte $48, $4d, $11, $ff, $bd, $48, $4d, $0c, $ff, $bd, $48, $4d, $0f, $ff, $bd, $48, $4d, $11, $ff, $bd, $48, $4d, $1b, $ff
	.byte $bd, $48, $4b, .lobyte(@env6), .hibyte(@env6), $4c, $80
	.byte $41, $42
	.word @song0ref39
	.byte $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch1loop:
	.byte $4c, $00, $ff, $bd, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $7a, $80
@song0ref213:
	.byte $11, $95, $0c, $95, $14, $95, $0f, $95, $18, $95, $14, $95, $1b, $95, $18, $95, $1d, $dd, $20, $ad, $1d, $ad, $1f, $dd
	.byte $1d, $ad, $1b, $ad, $1d, $ad, $18, $dd, $13, $ad, $0c, $95, $08, $95, $0f, $95, $0a, $95, $13, $95, $0f, $95, $18, $95
	.byte $13, $95, $1f, $dd, $1b, $dd, $1d, $ad, $18, $dd, $16, $ad, $18, $ad, $13, $dd, $0f, $ad
	.byte $41, $42
	.word @song0ref213
	.byte $7f, $4b, .lobyte(@env2), .hibyte(@env2), $82
@song0ref287:
	.byte $16, $ff, $bd, $4d, $19, $ff, $bd, $4d, $1d, $ff, $bd, $4d, $22, $ff, $bd, $4d, $11, $ff, $bd, $4d, $14, $ff, $bd, $4d
	.byte $18, $ff, $bd, $4d, $24, $ff, $bd, $4d
	.byte $41, $18
	.word @song0ref287
	.byte $42
	.word @song0ch1loop
@song0ch2:
	.byte $86
@song0ref326:
	.byte $0a, $ff, $bd, $16, $ff, $bd, $11, $ff, $bd, $1d, $dd, $18, $dd, $16, $ff, $bd, $0a, $ff, $bd, $11, $dd, $16, $dd, $14
	.byte $dd, $18, $dd
@song0ch2loop:
@song0ref354:
	.byte $0a, $dd, $11, $dd, $16, $ff, $bd, $18, $dd, $14, $dd, $1d, $dd, $18, $dd, $16, $ff, $bd, $0a, $ff, $bd, $11, $dd, $16
	.byte $dd, $14, $dd, $18, $dd
	.byte $41, $1d
	.word @song0ref354
	.byte $41, $1d
	.word @song0ref354
	.byte $41, $1b
	.word @song0ref326
	.byte $41, $1b
	.word @song0ref326
	.byte $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $75, $ff, $8f, $84, $2e, $95, $2e, $89, $2e, $89
@song0ch3loop:
@song0ref423:
	.byte $2e, $95, $2e, $95, $2e, $a1, $2e, $89, $2e, $95, $2e, $95, $2e, $89, $2e, $95, $2e, $89, $2e, $a1, $2e, $89, $2e, $89
	.byte $2e, $95, $2e, $95, $2e, $a1, $2e, $95, $2e, $89, $2e, $89
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $8b, $00, $ff, $b1, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $41, $24
	.word @song0ref423
	.byte $42
	.word @song0ch3loop
@song0ch4:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $01, $ad, $01, $ad, $01, $ad, $02, $95, $02, $89
	.byte $02, $89
@song0ch4loop:
@song0ref552:
	.byte $01, $95, $01, $95, $02, $95, $01, $95, $01, $a1, $01, $89, $02, $95, $01, $95, $01, $95, $01, $95, $02, $95, $01, $95
	.byte $01, $a1, $01, $89, $02, $95, $01, $95
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $41, $20
	.word @song0ref552
	.byte $42
	.word @song0ch4loop
@song1ch0:
	.byte $d5
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $7a, $80, $22, $93, $29, $93, $29, $93, $2b, $91, $48, $29
	.byte $93, $27, $93, $27, $93, $2b, $91, $48, $2c, $93, $30, $93, $33, $93, $30, $91, $48, $30, $93, $2e, $93, $2e, $a7, $48
	.byte $30, $93, $26, $93, $26, $93, $30, $91, $48, $2e, $93, $27, $93, $27, $93, $2b, $91, $48, $2b, $93, $29, $93, $2b, $93
	.byte $29, $91, $48, $2b, $93, $29, $93, $2b, $93, $29, $91, $42
	.word @song1ch0loop
@song1ch1:
	.byte $d5
@song1ch1loop:
	.byte $77, $80, $1d, $93, $24, $93, $24, $93, $26, $91, $24, $93, $22, $93, $22, $93, $26, $91, $27, $93, $2b, $93, $2e, $93
	.byte $2b, $91, $2b, $93, $29, $93, $29, $a7, $2b, $93, $21, $93, $21, $93, $2b, $91, $29, $93, $22, $93, $22, $93, $26, $91
	.byte $26, $93, $24, $93, $26, $93, $24, $91, $26, $93, $24, $93, $26, $93, $24, $91, $42
	.word @song1ch1loop
@song1ch2:
	.byte $d5
@song1ch2loop:
	.byte $84
@song1ref152:
	.byte $20, $93, $20, $93, $20, $93, $20, $91, $1f, $93, $1f, $93, $1f, $93, $20, $91, $24, $93, $24, $93, $24, $93, $24, $91
	.byte $22, $93, $22, $93, $22, $93, $22, $91
	.byte $41, $0e
	.word @song1ref152
	.byte $1f, $91, $18, $93, $18, $93, $18, $93, $18, $91, $1a, $93, $1a, $93, $1a, $93, $1a, $91, $42
	.word @song1ch2loop
@song1ch3:
	.byte $76, $88, $1f, $89, $1f, $87, $1f, $89, $1f, $87, $1f, $a7
@song1ch3loop:
@song1ref221:
	.byte $1b, $93, $1f, $93, $1b, $93, $1f, $91, $1b, $93, $1f, $93, $1b, $93, $1f, $91
	.byte $41, $10
	.word @song1ref221
	.byte $41, $10
	.word @song1ref221
	.byte $41, $10
	.word @song1ref221
	.byte $42
	.word @song1ch3loop
@song1ch4:
	.byte $02, $89, $02, $87, $02, $89, $02, $87, $02, $a7
@song1ch4loop:
@song1ref260:
	.byte $01, $93, $02, $93, $01, $93, $02, $91, $01, $93, $02, $93, $01, $93, $02, $91
	.byte $41, $10
	.word @song1ref260
	.byte $41, $10
	.word @song1ref260
	.byte $41, $10
	.word @song1ref260
	.byte $42
	.word @song1ch4loop
